# Generated by Django 4.2.21 on 2025-05-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='nume',
            new_name='nume_familie',
        ),
        migrations.AddField(
            model_name='doctor',
            name='prenume',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
