# Generated by Django 4.2.21 on 2025-05-21 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0002_rename_nume_doctor_nume_familie_doctor_prenume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('data_trimitere', models.DateTimeField(auto_now_add=True)),
                ('expeditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('programare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesaje', to='website.programare')),
            ],
        ),
    ]
