# Generated by Django 4.2.21 on 2025-06-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_secretariat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programare',
            name='serviciu',
        ),
    ]
