# Generated by Django 4.2.21 on 2025-06-07 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_consultatie_interventie'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasaInterventie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='interventie',
            name='clasa',
        ),
        migrations.RemoveField(
            model_name='interventie',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='interventie',
            name='denumire',
        ),
        migrations.CreateModel(
            name='InterventieCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('clasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventii', to='website.clasainterventie')),
            ],
        ),
        migrations.AddField(
            model_name='interventie',
            name='interventie_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website.interventiecatalog'),
        ),
    ]
