# Generated by Django 4.2.21 on 2025-06-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_clasainterventie_remove_interventie_clasa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultatie',
            name='dinte',
            field=models.CharField(max_length=50),
        ),
    ]
