# Generated by Django 4.2.21 on 2025-06-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_consultatie_dinte'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultatie',
            name='radiografie',
            field=models.ImageField(blank=True, help_text='Radiografie dentară (format: JPG, PNG, max 5MB)', null=True, upload_to='radiografii/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='consultatie',
            name='cost_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
